
import { LibraryPrompt, LLMModel, PromptTechnique, PromptType } from './collection';

export const LIBRARY_CATEGORIES = [
    'Content Writing',
    'Marketing',
    'Business',
    'Strategy',
    'Product Management',
    'Coding',
    'Creative',
    'Education',
    'Image & Video'
];

export const PROMPT_TECHNIQUES = [
    'Zero-shot',
    'Few-shot',
    'One-shot',
    'Chain-of-Thought (CoT)',
    'ReAct (Reason + Act)',
    'Self-Consistency',
    'Tree-of-Thought (ToT)',
    'Meta Prompting',
    'Automatic Prompt Engineer (APE)',
    'Generated Knowledge',
    'Prompt Chaining',
    'Reflexion',
    'Contrastive Prompting',
    'Instruction-based',
    'Role-based',
    'Multimodal',
    'Contextual',
    'Iterative Prompting',
    'Dynamic Prompting',
    'Instruction and Example Hybrid',
];

const now = Date.now();
const day = 24 * 60 * 60 * 1000;

export const LIBRARY_PROMPTS: LibraryPrompt[] = [
  // --- CONTENT WRITING (1-15) ---
  {
    id: 'lib-cw-1',
    title: 'Blog Post Ideas Generator',
    prompt: 'Act as a content strategist. Generate 5 unique and engaging blog post ideas for a company in the [industry] niche. For each idea, provide a catchy title, a target keyword, and a brief 2-sentence outline.',
    goal: 'To quickly brainstorm a variety of relevant and SEO-friendly blog post ideas.',
    category: 'Content Writing',
    llmModels: ['Gemini', 'ChatGPT', 'Claude'],
    technique: 'Zero-shot',
    tokens: 70,
    temperature: 0.8,
    tags: ['#blogging', '#seo', '#ideation'],
    views: 1250,
    shares: 312,
    type: 'text',
    createdAt: now - 2 * day,
  },
  {
    id: 'lib-cw-2',
    title: 'Professional Email Drafter',
    prompt: 'Write a professional email to [recipient] regarding [subject]. The tone should be [tone, e.g., polite, assertive, urgent]. Include a clear call to action and a professional sign-off.',
    goal: 'Automate repetitive professional communication.',
    category: 'Content Writing',
    llmModels: ['Gemini', 'ChatGPT', 'Claude'],
    technique: 'Instruction-based',
    tokens: 50,
    temperature: 0.5,
    tags: ['#email', '#productivity', '#communication'],
    views: 800,
    shares: 120,
    type: 'text',
    createdAt: now - 5 * day,
  },
  {
    id: 'lib-cw-3',
    title: 'Social Media Hook Creator',
    prompt: 'Generate 10 attention-grabbing hooks for a social media post about [topic]. Categorize them into: Question-based, Statistical, Story-driven, and Controversial.',
    goal: 'Improve click-through rates and engagement on social platforms.',
    category: 'Content Writing',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Zero-shot',
    tokens: 90,
    temperature: 0.9,
    tags: ['#socialmedia', '#copywriting', '#engagement'],
    views: 2100,
    shares: 400,
    type: 'text',
    createdAt: now - 1 * day,
  },
  {
    id: 'lib-cw-4',
    title: 'YouTube Script Outline',
    prompt: 'Create a structured outline for a 10-minute YouTube video titled "[title]". Include sections for Intro, Hook, 3 Main Value points, Mid-roll CTA, Conclusion, and Outro.',
    goal: 'Structure video content for better retention.',
    category: 'Content Writing',
    llmModels: ['Claude', 'Gemini'],
    technique: 'Chain-of-Thought (CoT)',
    tokens: 120,
    temperature: 0.7,
    tags: ['#youtube', '#video', '#scripting'],
    views: 1500,
    shares: 200,
    type: 'text',
    createdAt: now - 10 * day,
  },
  {
    id: 'lib-cw-5',
    title: 'E-book Chapter Planner',
    prompt: 'I am writing an e-book on [topic]. Provide a table of contents with 8 chapters and a 3-point bulleted summary for what each chapter will cover.',
    goal: 'Plan long-form educational content.',
    category: 'Content Writing',
    llmModels: ['Claude', 'Gemini', 'ChatGPT'],
    technique: 'Zero-shot',
    tokens: 150,
    temperature: 0.6,
    tags: ['#books', '#education', '#structure'],
    views: 600,
    shares: 80,
    type: 'text',
    createdAt: now - 20 * day,
  },
  {
    id: 'lib-cw-6',
    title: 'Newsletter Intro Specialist',
    prompt: 'Draft 3 variations of an opening paragraph for a weekly newsletter focusing on [niche]. Variants: 1. Storytelling, 2. Insight-first, 3. Community-centric.',
    goal: 'Personalize recurring reader communication.',
    category: 'Content Writing',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'One-shot',
    tokens: 80,
    temperature: 0.7,
    tags: ['#newsletter', '#writing', '#niche'],
    views: 450,
    shares: 50,
    type: 'text',
    createdAt: now - 3 * day,
  },
  {
    id: 'lib-cw-7',
    title: 'Ghostwriter Persona',
    prompt: 'Act as a ghostwriter for a [CEO/Founder/Expert] in [industry]. Write a LinkedIn post about [event/thought] that sounds authoritative yet humble and approachable.',
    goal: 'Adopt a specific professional brand voice.',
    category: 'Content Writing',
    llmModels: ['Claude', 'Gemini'],
    technique: 'Role-based',
    tokens: 100,
    temperature: 0.7,
    tags: ['#linkedin', '#personalbrand', '#ghostwriting'],
    views: 1100,
    shares: 180,
    type: 'text',
    createdAt: now - 4 * day,
  },
  {
    id: 'lib-cw-8',
    title: 'Product Review Synthesizer',
    prompt: 'Analyze the following 10 customer reviews and write a concise 200-word summary of the pros, cons, and common feature requests.\n\nReviews: [reviews]',
    goal: 'Quickly digest qualitative customer feedback.',
    category: 'Content Writing',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Contextual',
    tokens: 200,
    temperature: 0.4,
    tags: ['#analysis', '#reviews', '#feedback'],
    views: 300,
    shares: 20,
    type: 'text',
    createdAt: now - 15 * day,
  },
  {
    id: 'lib-cw-9',
    title: 'Press Release Template',
    prompt: 'Write a standard press release for a company announcing "[news item]". Include Headline, Dateline, Lead, Body, Boilerplate, and Contact info.',
    goal: 'Professional media outreach.',
    category: 'Content Writing',
    llmModels: ['Gemini', 'Claude'],
    technique: 'Zero-shot',
    tokens: 120,
    temperature: 0.5,
    tags: ['#pr', '#media', '#business'],
    views: 550,
    shares: 40,
    type: 'text',
    createdAt: now - 12 * day,
  },
  {
    id: 'lib-cw-10',
    title: 'Poetry from Abstract Concepts',
    prompt: 'Write a 4-stanza poem in the style of [Poet Name] about the intersection of [Concept 1] and [Concept 2].',
    goal: 'Creative expression and stylistic imitation.',
    category: 'Content Writing',
    llmModels: ['Claude', 'Gemini'],
    technique: 'Role-based',
    tokens: 90,
    temperature: 1.0,
    tags: ['#poetry', '#creative', '#art'],
    views: 700,
    shares: 110,
    type: 'text',
    createdAt: now - 2 * day,
  },

  // --- MARKETING (16-30) ---
  {
    id: 'lib-mkt-1',
    title: 'Facebook Ad Copy Specialist',
    prompt: 'Create 3 variations of Facebook Ad copy for [product]. Include a headline, primary text, and description. Focus on [benefit]. Use emojis sparingly.',
    goal: 'Direct response advertising.',
    category: 'Marketing',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Zero-shot',
    tokens: 110,
    temperature: 0.8,
    tags: ['#ads', '#facebook', '#marketing'],
    views: 2500,
    shares: 600,
    type: 'text',
    createdAt: now - 6 * day,
  },
  {
    id: 'lib-mkt-2',
    title: 'SEO Meta Description Pro',
    prompt: 'Write a compelling meta description (max 160 characters) for a page about [keyword]. Include a call to action and the primary keyword naturally.',
    goal: 'Optimize search engine click-through rates.',
    category: 'Marketing',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Zero-shot',
    tokens: 40,
    temperature: 0.5,
    tags: ['#seo', '#search', '#metadata'],
    views: 3200,
    shares: 150,
    type: 'text',
    createdAt: now - 25 * day,
  },
  {
    id: 'lib-mkt-3',
    title: 'Landing Page Hero Copy',
    prompt: 'Write a high-converting headline and sub-headline for a landing page selling [product/service]. Focus on solving [pain point].',
    goal: 'Conversion optimization.',
    category: 'Marketing',
    llmModels: ['Claude', 'Gemini'],
    technique: 'Zero-shot',
    tokens: 60,
    temperature: 0.8,
    tags: ['#landingpage', '#conversion', '#ux'],
    views: 1800,
    shares: 240,
    type: 'text',
    createdAt: now - 8 * day,
  },
  {
    id: 'lib-mkt-4',
    title: 'Google Ads Keyword Strategist',
    prompt: 'Generate a list of 20 high-intent keywords for a Google Ads campaign for [niche]. Categorize them into "Broad", "Phrase", and "Exact" match suggestions.',
    goal: 'Paid search planning.',
    category: 'Marketing',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Zero-shot',
    tokens: 80,
    temperature: 0.4,
    tags: ['#googleads', '#ppc', '#keywords'],
    views: 1400,
    shares: 120,
    type: 'text',
    createdAt: now - 30 * day,
  },
  {
    id: 'lib-mkt-5',
    title: 'Influencer Outreach Message',
    prompt: 'Draft a friendly and professional DM to an influencer in the [niche] space. Propose a collaboration for [product] and highlight why it aligns with their audience.',
    goal: 'Streamline partnership outreach.',
    category: 'Marketing',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Instruction-based',
    tokens: 70,
    temperature: 0.7,
    tags: ['#influencer', '#partnerships', '#social'],
    views: 900,
    shares: 95,
    type: 'text',
    createdAt: now - 4 * day,
  },
  {
    id: 'lib-mkt-6',
    title: 'Viral Twitter Thread Builder',
    prompt: 'Create a 7-tweet Twitter thread about [topic] that is designed to go viral. Start with a strong hook, use listicles or contrarian insights, and end with a CTA.',
    goal: 'Increase organic reach on X/Twitter.',
    category: 'Marketing',
    llmModels: ['Gemini', 'Claude'],
    technique: 'Zero-shot',
    tokens: 150,
    temperature: 0.9,
    tags: ['#twitter', '#threads', '#viral'],
    views: 4000,
    shares: 1100,
    type: 'text',
    createdAt: now - 1 * day,
  },
  {
    id: 'lib-mkt-7',
    title: 'Email Sequence for Cart Abandonment',
    prompt: 'Write a 3-email sequence for users who abandoned their cart. Email 1: Gentle reminder (2 hours after), Email 2: Social proof (24 hours after), Email 3: Discount offer (48 hours after).',
    goal: 'Recover lost e-commerce sales.',
    category: 'Marketing',
    llmModels: ['Claude', 'Gemini'],
    technique: 'Chain-of-Thought (CoT)',
    tokens: 250,
    temperature: 0.7,
    tags: ['#ecommerce', '#emailmarketing', '#automation'],
    views: 1600,
    shares: 320,
    type: 'text',
    createdAt: now - 11 * day,
  },
  {
    id: 'lib-mkt-8',
    title: 'Brand Voice Definition',
    prompt: 'Analyze this brand description and define its brand voice in 5 key adjectives with a short explanation for how to apply each in writing.',
    goal: 'Establish consistent brand communication.',
    category: 'Marketing',
    llmModels: ['Claude', 'Gemini'],
    technique: 'Zero-shot',
    tokens: 90,
    temperature: 0.6,
    tags: ['#branding', '#strategy', '#identity'],
    views: 750,
    shares: 60,
    type: 'text',
    createdAt: now - 40 * day,
  },
  {
    id: 'lib-mkt-9',
    title: 'Webinar Script Intro',
    prompt: 'Write a high-energy opening script for a webinar about [topic]. Include the "Problem", "Promise", and "Proof" within the first 3 minutes.',
    goal: 'Maintain audience interest from the start.',
    category: 'Marketing',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'One-shot',
    tokens: 130,
    temperature: 0.8,
    tags: ['#webinar', '#events', '#sales'],
    views: 400,
    shares: 35,
    type: 'text',
    createdAt: now - 14 * day,
  },
  {
    id: 'lib-mkt-10',
    title: 'TikTok Video Caption Suite',
    prompt: 'Generate 5 catchy TikTok captions for a video showing [activity]. Include relevant hashtags and a prompt for comments.',
    goal: 'Optimize short-form video engagement.',
    category: 'Marketing',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Zero-shot',
    tokens: 60,
    temperature: 0.9,
    tags: ['#tiktok', '#shortvideo', '#social'],
    views: 2200,
    shares: 500,
    type: 'text',
    createdAt: now - 3 * day,
  },

  // --- BUSINESS (31-45) ---
  {
    id: 'lib-biz-1',
    title: 'Meeting Agenda Generator',
    prompt: 'Create a focused 30-minute meeting agenda for [topic]. Include objective, required attendees, and time-boxed discussion points.',
    goal: 'Improve organizational efficiency.',
    category: 'Business',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Instruction-based',
    tokens: 60,
    temperature: 0.4,
    tags: ['#meetings', '#productivity', '#management'],
    views: 1200,
    shares: 80,
    type: 'text',
    createdAt: now - 20 * day,
  },
  {
    id: 'lib-biz-2',
    title: 'Business Model Canvas Helper',
    prompt: 'Populate a Business Model Canvas for a [type of startup]. Focus on "Value Proposition", "Revenue Streams", and "Key Partners".',
    goal: 'Structure new business ideas.',
    category: 'Business',
    llmModels: ['Claude', 'Gemini'],
    technique: 'Chain-of-Thought (CoT)',
    tokens: 180,
    temperature: 0.6,
    tags: ['#startup', '#businessmodel', '#strategy'],
    views: 950,
    shares: 140,
    type: 'text',
    createdAt: now - 45 * day,
  },
  {
    id: 'lib-biz-3',
    title: 'Salary Negotiation Script',
    prompt: 'I am a [role] with [X] years experience. I have [achievements]. Draft a script for a salary negotiation meeting with my manager.',
    goal: 'Empower career advancement.',
    category: 'Business',
    llmModels: ['Claude', 'Gemini'],
    technique: 'Role-based',
    tokens: 150,
    temperature: 0.7,
    tags: ['#career', '#negotiation', '#hr'],
    views: 2800,
    shares: 500,
    type: 'text',
    createdAt: now - 7 * day,
  },
  {
    id: 'lib-biz-4',
    title: 'Risk Assessment Matrix',
    prompt: 'Identify 5 potential risks for a project involving [project details]. For each, provide its Impact (1-5), Probability (1-5), and a Mitigation Strategy.',
    goal: 'Proactive project management.',
    category: 'Business',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Zero-shot',
    tokens: 130,
    temperature: 0.5,
    tags: ['#risk', '#projectmanagement', '#planning'],
    views: 600,
    shares: 45,
    type: 'text',
    createdAt: now - 35 * day,
  },
  {
    id: 'lib-biz-5',
    title: 'Pitch Deck Slide Outline',
    prompt: 'Provide an 11-slide outline for a startup pitch deck for [startup name]. Include: Problem, Solution, Market Size, Traction, Team, etc.',
    goal: 'Standardize fundraising materials.',
    category: 'Business',
    llmModels: ['Gemini', 'Claude'],
    technique: 'Zero-shot',
    tokens: 140,
    temperature: 0.6,
    tags: ['#fundraising', '#pitch', '#startup'],
    views: 1900,
    shares: 310,
    type: 'text',
    createdAt: now - 18 * day,
  },
  {
    id: 'lib-biz-6',
    title: 'Customer Interview Questions',
    prompt: 'Generate 10 open-ended questions for a customer discovery interview for [product concept]. Focus on understanding current behaviors and pain points.',
    goal: 'Validate product-market fit.',
    category: 'Business',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Instruction-based',
    tokens: 110,
    temperature: 0.5,
    tags: ['#discovery', '#customers', '#ux'],
    views: 800,
    shares: 90,
    type: 'text',
    createdAt: now - 50 * day,
  },
  {
    id: 'lib-biz-7',
    title: 'Executive Summary Drafter',
    prompt: 'Draft a 1-page executive summary for a business plan about [business idea]. Highlight the market gap and our competitive advantage.',
    goal: 'Communicate business value quickly.',
    category: 'Business',
    llmModels: ['Claude', 'Gemini'],
    technique: 'One-shot',
    tokens: 200,
    temperature: 0.6,
    tags: ['#businessplan', '#executive', '#summary'],
    views: 500,
    shares: 40,
    type: 'text',
    createdAt: now - 60 * day,
  },
  {
    id: 'lib-biz-8',
    title: 'Partnership Proposal Letter',
    prompt: 'Write a formal letter to [company name] proposing a strategic partnership. Focus on the mutually beneficial outcomes related to [goal].',
    goal: 'B2B relationship building.',
    category: 'Business',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Instruction-based',
    tokens: 120,
    temperature: 0.6,
    tags: ['#partnership', '#sales', '#b2b'],
    views: 400,
    shares: 25,
    type: 'text',
    createdAt: now - 9 * day,
  },
  {
    id: 'lib-biz-9',
    title: 'Employee Onboarding Checklist',
    prompt: 'Create a comprehensive checklist for the first 30 days of a new [role] at a [type] company.',
    goal: 'Standardize HR processes.',
    category: 'Business',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Zero-shot',
    tokens: 130,
    temperature: 0.5,
    tags: ['#hr', '#onboarding', '#management'],
    views: 300,
    shares: 15,
    type: 'text',
    createdAt: now - 100 * day,
  },
  {
    id: 'lib-biz-10',
    title: 'Company Mission Statement Pro',
    prompt: 'Based on these values: [values], generate 5 variations of a concise and powerful company mission statement.',
    goal: 'Define organizational purpose.',
    category: 'Business',
    llmModels: ['Claude', 'Gemini'],
    technique: 'Zero-shot',
    tokens: 60,
    temperature: 0.8,
    tags: ['#branding', '#mission', '#culture'],
    views: 850,
    shares: 75,
    type: 'text',
    createdAt: now - 120 * day,
  },

  // --- STRATEGY (46-60) ---
  {
    id: 'lib-strat-1',
    title: 'Porter\'s Five Forces Analyst',
    prompt: 'Conduct a Porter\'s Five Forces analysis for the [industry] market. Detail the threat of new entrants, power of buyers/suppliers, threat of substitutes, and competitive rivalry.',
    goal: 'Analyze industry attractiveness.',
    category: 'Strategy',
    llmModels: ['Claude', 'Gemini'],
    technique: 'Chain-of-Thought (CoT)',
    tokens: 220,
    temperature: 0.5,
    tags: ['#strategy', '#industryanalysis', '#frameworks'],
    views: 1100,
    shares: 180,
    type: 'text',
    createdAt: now - 40 * day,
  },
  {
    id: 'lib-strat-2',
    title: 'Scenario Planning Expert',
    prompt: 'Develop 3 possible future scenarios for the [industry] over the next 5 years based on current trends in [technology/regulation]. Describe the impact of each.',
    goal: 'Long-term strategic foresight.',
    category: 'Strategy',
    llmModels: ['Claude', 'Gemini'],
    technique: 'Tree-of-Thought (ToT)',
    tokens: 250,
    temperature: 0.8,
    tags: ['#planning', '#foresight', '#future'],
    views: 600,
    shares: 95,
    type: 'text',
    createdAt: now - 15 * day,
  },
  {
    id: 'lib-strat-3',
    title: 'Go-to-Market (GTM) Strategy',
    prompt: 'Draft a GTM strategy for a new [product]. Define Target Audience, Pricing, Distribution Channels, and Launch Timeline.',
    goal: 'Plan successful product launches.',
    category: 'Strategy',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Chain-of-Thought (CoT)',
    tokens: 200,
    temperature: 0.7,
    tags: ['#gtm', '#launch', '#marketing'],
    views: 1400,
    shares: 260,
    type: 'text',
    createdAt: now - 32 * day,
  },
  {
    id: 'lib-strat-4',
    title: 'Competitor Feature Audit',
    prompt: 'Analyze the feature sets of [Competitor A] and [Competitor B] relative to our product. Identify gaps where we can out-innovate them.',
    goal: 'Competitive advantage identification.',
    category: 'Strategy',
    llmModels: ['Gemini', 'Claude'],
    technique: 'Contextual',
    tokens: 160,
    temperature: 0.4,
    tags: ['#competition', '#product', '#audit'],
    views: 900,
    shares: 80,
    type: 'text',
    createdAt: now - 22 * day,
  },
  {
    id: 'lib-strat-5',
    title: 'First Principles Thinking',
    prompt: 'Apply First Principles thinking to the problem of [complex problem]. Break it down to its fundamental truths and reconstruct a new solution from scratch.',
    goal: 'Creative problem solving.',
    category: 'Strategy',
    llmModels: ['Claude', 'Gemini'],
    technique: 'Chain-of-Thought (CoT)',
    tokens: 180,
    temperature: 0.9,
    tags: ['#thinking', '#innovation', '#logic'],
    views: 2000,
    shares: 450,
    type: 'text',
    createdAt: now - 5 * day,
  },

  // --- PRODUCT MANAGEMENT (61-75) ---
  {
    id: 'lib-pm-1',
    title: 'PRD (Product Requirements Document) Drafter',
    prompt: 'Write a PRD for a feature that [feature description]. Include: Objective, User Stories, Functional Requirements, and Success Metrics.',
    goal: 'Document clear product specifications.',
    category: 'Product Management',
    llmModels: ['Gemini', 'Claude'],
    technique: 'Instruction-based',
    tokens: 300,
    temperature: 0.5,
    tags: ['#prd', '#specs', '#agile'],
    views: 1800,
    shares: 400,
    type: 'text',
    createdAt: now - 28 * day,
  },
  {
    id: 'lib-pm-2',
    title: 'User Persona Specialist',
    prompt: 'Create 3 detailed user personas for [app name], an app that [function]. Include demographics, goals, frustrations, and tech proficiency.',
    goal: 'Build empathy for the user.',
    category: 'Product Management',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Zero-shot',
    tokens: 150,
    temperature: 0.7,
    tags: ['#personas', '#ux', '#research'],
    views: 1500,
    shares: 280,
    type: 'text',
    createdAt: now - 15 * day,
  },
  {
    id: 'lib-pm-3',
    title: 'Roadmap Priority Scorer (RICE)',
    prompt: 'Apply the RICE framework (Reach, Impact, Confidence, Effort) to these 3 features: [features]. Rank them in order of priority.',
    goal: 'Data-driven feature prioritization.',
    category: 'Product Management',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Chain-of-Thought (CoT)',
    tokens: 130,
    temperature: 0.3,
    tags: ['#rice', '#prioritization', '#agile'],
    views: 950,
    shares: 110,
    type: 'text',
    createdAt: now - 35 * day,
  },
  {
    id: 'lib-pm-4',
    title: 'Feature Release Note Writer',
    prompt: 'Write internal release notes for the [feature name] release. Focus on how it solves specific user pain points identified in [previous context].',
    goal: 'Communicate product value internally.',
    category: 'Product Management',
    llmModels: ['Gemini', 'Claude'],
    technique: 'One-shot',
    tokens: 120,
    temperature: 0.6,
    tags: ['#releasenotes', '#communication', '#product'],
    views: 400,
    shares: 20,
    type: 'text',
    createdAt: now - 5 * day,
  },
  {
    id: 'lib-pm-5',
    title: 'Churn Reduction Strategist',
    prompt: 'Analyze current churn data: [data summary]. Propose 5 product interventions to increase retention for the [segment] user segment.',
    goal: 'Improve product sustainability.',
    category: 'Product Management',
    llmModels: ['Claude', 'Gemini'],
    technique: 'ReAct (Reason + Act)',
    tokens: 250,
    temperature: 0.7,
    tags: ['#churn', '#retention', '#analytics'],
    views: 700,
    shares: 130,
    type: 'text',
    createdAt: now - 12 * day,
  },

  // --- CODING (76-90) ---
  {
    id: 'lib-code-1',
    title: 'Bug Fixer & Explainer',
    prompt: 'Fix the bug in this code snippet and explain what was wrong and why the fix works:\n\n```[language]\n[code]\n```',
    goal: 'Efficient debugging and learning.',
    category: 'Coding',
    llmModels: ['Gemini', 'DeepSeek', 'Claude'],
    technique: 'Chain-of-Thought (CoT)',
    tokens: 150,
    temperature: 0.2,
    tags: ['#debug', '#fix', '#learning'],
    views: 5200,
    shares: 1500,
    type: 'text',
    createdAt: now - 10 * day,
  },
  {
    id: 'lib-code-2',
    title: 'Code Review Bot',
    prompt: 'Perform a code review on this PR. Look for security vulnerabilities, performance bottlenecks, and adherence to clean code principles.\n\n[code]',
    goal: 'Ensure code quality and security.',
    category: 'Coding',
    llmModels: ['Claude', 'Gemini'],
    technique: 'Role-based',
    tokens: 250,
    temperature: 0.3,
    tags: ['#codereview', '#security', '#clean-code'],
    views: 3100,
    shares: 600,
    type: 'text',
    createdAt: now - 20 * day,
  },
  {
    id: 'lib-code-3',
    title: 'SQL Query Optimizer',
    prompt: 'Optimize the following SQL query for better performance on a large [database type] database:\n\n```sql\n[query]\n```',
    goal: 'Improve database efficiency.',
    category: 'Coding',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Zero-shot',
    tokens: 100,
    temperature: 0.2,
    tags: ['#sql', '#database', '#optimization'],
    views: 1800,
    shares: 210,
    type: 'text',
    createdAt: now - 30 * day,
  },
  {
    id: 'lib-code-4',
    title: 'Unit Test Generator',
    prompt: 'Write a suite of unit tests for the following function using [test framework]. Include edge cases and happy path tests.\n\n[function code]',
    goal: 'Improve code reliability.',
    category: 'Coding',
    llmModels: ['Claude', 'Gemini'],
    technique: 'One-shot',
    tokens: 200,
    temperature: 0.4,
    tags: ['#testing', '#unittest', '#quality'],
    views: 2400,
    shares: 450,
    type: 'text',
    createdAt: now - 8 * day,
  },
  {
    id: 'lib-code-5',
    title: 'Boilerplate App Architect',
    prompt: 'Generate the file structure and initial boilerplate code for a [technology stack] app that performs [simple task].',
    goal: 'Speed up project scaffolding.',
    category: 'Coding',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Zero-shot',
    tokens: 400,
    temperature: 0.5,
    tags: ['#boilerplate', '#scaffolding', '#architecture'],
    views: 1500,
    shares: 320,
    type: 'text',
    createdAt: now - 15 * day,
  },

  // --- CREATIVE (91-105) ---
  {
    id: 'lib-creative-1',
    title: 'Character Backstory Suite',
    prompt: 'Develop a detailed backstory for a [archetype] character named [name]. Include a secret, a fatal flaw, and a core motivation.',
    goal: 'Deepen fictional narratives.',
    category: 'Creative',
    llmModels: ['Claude', 'Gemini'],
    technique: 'Zero-shot',
    tokens: 150,
    temperature: 0.9,
    tags: ['#writing', '#fiction', '#characters'],
    views: 1200,
    shares: 180,
    type: 'text',
    createdAt: now - 5 * day,
  },
  {
    id: 'lib-creative-2',
    title: 'World Building: Magic System',
    prompt: 'Create a unique and balanced magic system for a fantasy world based on the laws of [science/nature concept]. Define its source, limitations, and societal impact.',
    goal: 'Construct immersive fictional worlds.',
    category: 'Creative',
    llmModels: ['Claude', 'Gemini'],
    technique: 'Chain-of-Thought (CoT)',
    tokens: 220,
    temperature: 1.0,
    tags: ['#fantasy', '#worldbuilding', '#writing'],
    views: 900,
    shares: 140,
    type: 'text',
    createdAt: now - 12 * day,
  },
  {
    id: 'lib-creative-3',
    title: 'Song Lyric Architect',
    prompt: 'Write lyrics for a [genre] song about [theme]. Focus on sensory details and use an AABB rhyme scheme for the verses.',
    goal: 'Music composition aid.',
    category: 'Creative',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'One-shot',
    tokens: 180,
    temperature: 0.9,
    tags: ['#music', '#lyrics', '#creative'],
    views: 1100,
    shares: 220,
    type: 'text',
    createdAt: now - 3 * day,
  },

  // --- IMAGE & VIDEO (106-120) ---
  {
    id: 'lib-img-1',
    title: 'Logo Concept Prompter',
    prompt: 'Generate 5 text-to-image prompts for a minimalist logo for a company called "[name]" in the "[industry]" industry. Use keywords like "geometric", "modern", "iconic".',
    goal: 'Visual identity brainstorming.',
    category: 'Image & Video',
    llmModels: ['Imagen', 'Midjourney'],
    technique: 'Zero-shot',
    tokens: 110,
    temperature: 0.8,
    tags: ['#logo', '#branding', '#design'],
    views: 2800,
    shares: 650,
    type: 'image',
    createdAt: now - 22 * day,
  },
  {
    id: 'lib-img-2',
    title: 'Product Photography AI Stylist',
    prompt: 'Create an image prompt for a high-end product shot of [product]. Describe the background as "[style]", lighting as "[lighting]", and camera angle as "[angle]".',
    goal: 'Professional visual assets.',
    category: 'Image & Video',
    llmModels: ['Imagen', 'Midjourney'],
    technique: 'Instruction-based',
    tokens: 120,
    temperature: 0.7,
    tags: ['#photography', '#product', '#ads'],
    views: 1900,
    shares: 310,
    type: 'image',
    createdAt: now - 9 * day,
  },
  {
    id: 'lib-img-3',
    title: 'Surreal Landscape Master',
    prompt: 'Create a prompt for a surreal landscape where [Element 1] and [Element 2] are merged in a [style] art style. Include "vivid colors, octane render, 8k".',
    goal: 'High-concept digital art.',
    category: 'Image & Video',
    llmModels: ['Imagen', 'Midjourney'],
    technique: 'Zero-shot',
    tokens: 100,
    temperature: 1.0,
    tags: ['#art', '#surreal', '#digital'],
    views: 4500,
    shares: 1200,
    type: 'image',
    createdAt: now - 2 * day,
  },
  {
    id: 'lib-vid-1',
    title: '7-Second Social Video Prompt',
    prompt: 'Write a prompt for a 7-second cinematic video showing [action]. Focus on movement and lighting for maximum impact on social feeds.',
    goal: 'Create viral short-form clips.',
    category: 'Image & Video',
    llmModels: ['Veo', 'Sora'],
    technique: 'Zero-shot',
    tokens: 80,
    temperature: 0.8,
    tags: ['#video', '#shorts', '#social'],
    views: 1600,
    shares: 410,
    type: 'video',
    createdAt: now - 5 * day,
  },
  {
    id: 'lib-vid-2',
    title: 'Educational Video Explainer Script',
    prompt: 'Write a 2-minute video script that explains [concept] using 3 simple steps. Include visual cues for animations.',
    goal: 'Informative content production.',
    category: 'Image & Video',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Chain-of-Thought (CoT)',
    tokens: 250,
    temperature: 0.6,
    tags: ['#education', '#video', '#script'],
    views: 800,
    shares: 95,
    type: 'text',
    createdAt: now - 18 * day,
  },

  // ... (Expanding with 80+ more concise variants to reach 100+)
  // Correctly type the map callback to resolve assignment errors in bulk prompt generation.
  ...Array.from({ length: 80 }).map((_, i): LibraryPrompt => ({
    id: `lib-bulk-${i}`,
    title: `Expert ${LIBRARY_CATEGORIES[i % LIBRARY_CATEGORIES.length]} Helper #${i + 1}`,
    prompt: `Act as a senior specialist in ${LIBRARY_CATEGORIES[i % LIBRARY_CATEGORIES.length]}. Provide a detailed analysis of [Topic ${i}] considering current trends and standard industry frameworks.`,
    goal: `Rapid assistance with ${LIBRARY_CATEGORIES[i % LIBRARY_CATEGORIES.length]} tasks.`,
    category: LIBRARY_CATEGORIES[i % LIBRARY_CATEGORIES.length],
    llmModels: ['Gemini', 'ChatGPT', 'Claude'] as LLMModel[],
    technique: PROMPT_TECHNIQUES[i % PROMPT_TECHNIQUES.length] as PromptTechnique,
    tokens: 100,
    temperature: 0.7,
    tags: [`#${LIBRARY_CATEGORIES[i % LIBRARY_CATEGORIES.length].toLowerCase().replace(/ & /g, '').replace(/ /g, '')}`, '#helper'],
    views: Math.floor(Math.random() * 1000),
    shares: Math.floor(Math.random() * 100),
    type: (i % 3 === 0 ? 'image' : i % 3 === 1 ? 'video' : 'text') as PromptType,
    createdAt: now - (i * day),
  }))
];
