

import { LibraryPrompt } from './collection';

export const LIBRARY_CATEGORIES = [
    'Content Writing',
    'Marketing',
    'Business',
    'Strategy',
    'Product Management',
    'Coding',
    'Creative',
    'Education',
    'Image & Video'
];

export const PROMPT_TECHNIQUES = [
    // Core
    'Zero-shot',
    'Few-shot',
    'One-shot',
    'Chain-of-Thought (CoT)',
    'ReAct (Reason + Act)',
    'Self-Consistency',
    'Tree-of-Thought (ToT)',
    'Meta Prompting',
    'Automatic Prompt Engineer (APE)',
    'Generated Knowledge',
    // Advanced / Specialized
    'Prompt Chaining',
    'Reflexion',
    'Contrastive Prompting',
    'Instruction-based',
    'Role-based',
    'Multimodal',
    'Contextual',
    'Iterative Prompting',
    'Dynamic Prompting',
    'Instruction and Example Hybrid',
];

export const LIBRARY_PROMPTS: LibraryPrompt[] = [
  // --- CONTENT WRITING ---
  {
    id: 'lib-cw-1',
    title: 'Blog Post Ideas Generator',
    prompt: 'Act as a content strategist. Generate 5 unique and engaging blog post ideas for a company in the [industry] niche. For each idea, provide a catchy title, a target keyword, and a brief 2-sentence outline explaining the angle of the post.',
    goal: 'To quickly brainstorm a variety of relevant and SEO-friendly blog post ideas with a clear starting point for writing.',
    category: 'Content Writing',
    llmModels: ['Gemini', 'ChatGPT', 'Claude'],
    technique: 'Zero-shot',
    tokens: 70,
    temperature: 0.8,
    tags: ['#blogging', '#seo', '#ideation'],
    views: 1250,
    shares: 312,
    type: 'text',
    createdAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'lib-cw-2',
    title: 'Article Rewriter and Enhancer',
    prompt: 'Rewrite the following article to have a more [e.g., professional, casual, witty] tone. Improve the flow and clarity, correct any grammatical errors, and suggest a more compelling headline. Do not change the core information or data presented.\n\n---\n\n[Paste article text here]',
    goal: 'To repurpose existing content by changing its tone and improving its readability without altering the factual information.',
    category: 'Content Writing',
    llmModels: ['Gemini', 'Claude', 'Llama'],
    technique: 'Zero-shot',
    tokens: 80,
    temperature: 0.7,
    tags: ['#editing', '#rewriting', '#tone'],
    views: 980,
    shares: 155,
    type: 'text',
    createdAt: Date.now() - 15 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'lib-cw-3',
    title: 'FAQ Content Creator',
    prompt: 'Generate a list of 10 frequently asked questions (FAQs) for a website that sells [product/service]. For each question, provide a clear, concise, and helpful answer. The tone should be supportive and easy to understand for a non-expert audience.',
    goal: 'To create a comprehensive FAQ section that addresses common customer questions, reducing support tickets and building trust.',
    category: 'Content Writing',
    llmModels: ['Gemini', 'ChatGPT', 'Co-pilot'],
    technique: 'Zero-shot',
    tokens: 65,
    temperature: 0.6,
    tags: ['#faq', '#support', '#website-content'],
    views: 1100,
    shares: 230,
    type: 'text',
    createdAt: Date.now() - 18 * 24 * 60 * 60 * 1000,
  },

  // --- MARKETING ---
  {
    id: 'lib-mkt-1',
    title: 'AIDA Framework Ad Copy',
    prompt: 'Write a compelling short-form ad copy for a new [product] using the AIDA framework.\n\n- Attention: Grab the attention of [target audience].\n- Interest: Pique their interest by highlighting a key problem or benefit.\n- Desire: Create desire by explaining the unique value proposition.\n- Action: End with a clear and urgent call to action.',
    goal: 'To create a persuasive and structured ad copy that effectively guides a potential customer towards taking a desired action.',
    category: 'Marketing',
    llmModels: ['Gemini', 'ChatGPT', 'Claude'],
    technique: 'Chain-of-Thought (CoT)',
    tokens: 85,
    temperature: 0.9,
    tags: ['#advertising', '#copywriting', '#aida'],
    views: 2100,
    shares: 520,
    type: 'text',
    createdAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'lib-mkt-2',
    title: 'Social Media Content Calendar',
    prompt: 'Create a 5-day social media content calendar for an Instagram account focused on [topic]. The goal is to increase engagement. For each day, provide a content theme (e.g., "Myth-busting Monday"), a specific post idea, a compelling caption, and 3-5 relevant hashtags.',
    goal: 'To generate a structured and engaging content plan for social media, saving time and ensuring consistent posting.',
    category: 'Marketing',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Zero-shot',
    tokens: 80,
    temperature: 0.8,
    tags: ['#social-media', '#instagram', '#content-planning'],
    views: 1800,
    shares: 450,
    type: 'text',
    createdAt: Date.now() - 12 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'lib-mkt-3',
    title: 'Value Proposition Builder',
    prompt: 'Analyze the following product description and extract a clear and concise value proposition. Frame it in a single sentence that answers the question: "What does this product do and for whom, and why is it better than alternatives?"\n\nProduct Description: [Paste a detailed product description here]',
    goal: 'To distill a complex product description into a powerful, single-sentence value proposition for use in marketing materials.',
    category: 'Marketing',
    llmModels: ['Gemini', 'Claude'],
    technique: 'Zero-shot',
    tokens: 70,
    temperature: 0.6,
    tags: ['#branding', '#strategy', '#value-proposition'],
    views: 1400,
    shares: 280,
    type: 'text',
    createdAt: Date.now() - 25 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'lib-mkt-4',
    title: 'Customer Pain Point Detective',
    prompt: 'Act like a seasoned Market Insight Analyst. You have been providing market research and analysis for health and wellness products for 20 years. \n\nObjective: I am passionate about [Interest/Niche] and have noticed a rise in people seeking solutions. I want to find a product to cater to this market.\n\nStep-by-step process:\n1. Guide me to identify top recurring complaints/frustrations in online forums (e.g., Reddit).\n2. For each problem, brainstorm 2-3 potential product types.\n3. Explain how to use Google Trends to gauge search interest.\n4. Help analyze the data to make an informed decision.',
    goal: 'To uncover hidden consumer pain points and brainstorm product solutions.',
    category: 'Marketing',
    llmModels: ['ChatGPT', 'Gemini'],
    technique: 'Role-based',
    tokens: 150,
    temperature: 0.7,
    tags: ['#market-research', '#pain-points', '#product-ideas'],
    views: 0,
    shares: 0,
    type: 'text',
    createdAt: Date.now(),
  },
  {
    id: 'lib-mkt-5',
    title: 'Social Proof Strategy Architect',
    prompt: 'Act as a Social Validation Architect. I am launching a [Product Type].\n\nPlan out 3 specific ways I can gather social proof for its launch BEFORE I even have the product fully ready.\nOptions to consider: Early customer testimonials (in exchange for discount), showcasing user-generated content, partnering with micro-influencers.\n\nAnalyze which method would be most trustworthy for my target audience: [Target Audience].',
    goal: 'To build trust and authority for a new product launch using psychological social proof triggers.',
    category: 'Marketing',
    llmModels: ['Claude', 'Gemini'],
    technique: 'Role-based',
    tokens: 120,
    temperature: 0.8,
    tags: ['#launch', '#social-proof', '#marketing-strategy'],
    views: 0,
    shares: 0,
    type: 'text',
    createdAt: Date.now(),
  },
  {
    id: 'lib-mkt-6',
    title: 'Loss Aversion Marketing Re-framer',
    prompt: 'Act as a Problem-Solving Strategist expert in consumer psychology.\n\nProduct: [Product Name].\nCore Benefit: [Benefit].\n\nReframe this benefit using the "Loss Aversion" principle (people are more motivated to avoid loss than gain).\nInstead of "Gain X", frame it as "Stop losing Y".\n\nExample: Instead of "Get healthy", use "Stop letting fatigue ruin your weekends".\n\nWrite 3 ad headlines using this principle.',
    goal: 'To increase conversion rates by leveraging the psychological power of loss aversion.',
    category: 'Marketing',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Contextual',
    tokens: 130,
    temperature: 0.7,
    tags: ['#psychology', '#copywriting', '#conversion'],
    views: 0,
    shares: 0,
    type: 'text',
    createdAt: Date.now(),
  },
  {
    id: 'lib-mkt-7',
    title: 'Maslow\'s Hierarchy Customer Profiler',
    prompt: 'Act as a Customer Needs Profiler.\n\nTarget Customer: [Customer Description].\nProduct: [Product].\n\nUsing Maslow\'s Hierarchy of Needs, determine which level this product primarily addresses (Physiological, Safety, Belonging, Esteem, Self-Actualization).\n\nBrainstorm two marketing angles:\n1. Addressing a lower-level need (Safety/Practical).\n2. Addressing a higher-level need (Status/Aspirational).\n\nAnalyze which is more powerful for this specific customer.',
    goal: 'To connect with customers on a deeper psychological level by targeting specific needs.',
    category: 'Marketing',
    llmModels: ['Claude', 'Gemini'],
    technique: 'Role-based',
    tokens: 160,
    temperature: 0.7,
    tags: ['#psychology', '#branding', '#maslow'],
    views: 0,
    shares: 0,
    type: 'text',
    createdAt: Date.now(),
  },
  {
    id: 'lib-mkt-8',
    title: 'Scarcity & Urgency Architect',
    prompt: 'Act as a Strategic Sales Booster.\n\nAnalyze my product: [Product].\n\n1. Brainstorm an ETHICAL way to create scarcity (e.g., limited seats, limited materials, time-bound bonus).\n2. Draft 3 marketing phrases that convey Urgency without sounding spammy.\n3. Verify that this aligns with a [Brand Tone] brand image.',
    goal: 'To drive immediate action from customers using ethical scarcity and urgency tactics.',
    category: 'Marketing',
    llmModels: ['ChatGPT', 'Gemini'],
    technique: 'Role-based',
    tokens: 140,
    temperature: 0.8,
    tags: ['#sales', '#copywriting', '#conversion'],
    views: 0,
    shares: 0,
    type: 'text',
    createdAt: Date.now(),
  },
  {
    id: 'lib-mkt-9',
    title: 'Micro-Moment Marketing Planner',
    prompt: 'Act as a Customer Journey Mapper.\n\nProduct: [Product].\n\nIdentify 3 specific "Micro-Moments" (I want-to-know, I want-to-go, I want-to-do, I want-to-buy) where a user turns to their device for a split-second answer related to my niche.\n\nFor each moment, draft a Google Ad headline or Social Media hook that provides the immediate solution they are looking for.',
    goal: 'To capture customers at the exact moment of high intent.',
    category: 'Marketing',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Contextual',
    tokens: 150,
    temperature: 0.6,
    tags: ['#advertising', '#mobile-marketing', '#strategy'],
    views: 0,
    shares: 0,
    type: 'text',
    createdAt: Date.now(),
  },

  // --- BUSINESS ---
  {
    id: 'lib-biz-1',
    title: 'Elevator Pitch Generator',
    prompt: 'I am a [your role] at a company that [what your company does]. Our target customer is [target customer]. The main problem we solve is [problem]. Our unique solution is [unique solution]. Condense this information into a compelling 30-second elevator pitch.',
    goal: 'To create a concise, memorable, and persuasive summary of a business or project for networking and sales.',
    category: 'Business',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Zero-shot',
    tokens: 65,
    temperature: 0.7,
    tags: ['#sales', '#networking', '#pitch'],
    views: 1950,
    shares: 400,
    type: 'text',
    createdAt: Date.now() - 9 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'lib-biz-2',
    title: 'SWOT Analysis Assistant',
    prompt: 'Conduct a SWOT analysis for a [type of business, e.g., local coffee shop, SaaS startup] in the current market. Provide at least 3 bullet points for each of the following categories:\n\n- Strengths (Internal, positive factors)\n- Weaknesses (Internal, negative factors)\n- Opportunities (External, positive factors)\n- Threats (External, negative factors)',
    goal: 'To perform a structured strategic analysis, identifying key internal and external factors that can impact a business.',
    category: 'Business',
    llmModels: ['Gemini', 'Claude'],
    technique: 'Chain-of-Thought (CoT)',
    tokens: 90,
    temperature: 0.6,
    tags: ['#strategy', '#business-analysis', '#swot'],
    views: 2200,
    shares: 380,
    type: 'text',
    createdAt: Date.now() - 22 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'lib-biz-3',
    title: 'Comprehensive Niche Business Generator',
    prompt: 'Act like an experienced business strategist. You have been assisting entrepreneurs in identifying and developing niche business ideas for 20 years.\n\nI possess skills in: [Skill 1], [Skill 2].\nI am passionate about: [Passion 1], [Passion 2].\n\nBased on these, generate 5 niche business ideas with high potential. For each idea, provide:\n1. Market Opportunity\n2. Target Audience\n3. Competitive Analysis\n4. Revenue Potential\n5. Challenges and Risks',
    goal: 'To generate validated business ideas based on personal skills and market needs.',
    category: 'Business',
    llmModels: ['Claude', 'ChatGPT', 'Gemini'],
    technique: 'Role-based',
    tokens: 200,
    temperature: 0.7,
    tags: ['#entrepreneurship', '#startup', '#ideation'],
    views: 0,
    shares: 0,
    type: 'text',
    createdAt: Date.now(),
  },
  {
    id: 'lib-biz-4',
    title: 'Bangladeshi Market Localization Expert',
    prompt: 'Act as a Local Market Researcher for Bangladesh.\n\nI want to adapt a global business concept: [Global Concept/Trend].\n\nAnalyze the feasibility in Bangladesh considering:\n1. Socioeconomic Factors (Price sensitivity, income brackets)\n2. Cultural Fit (Family dynamics, traditions)\n3. Local Logistics (Payment methods, delivery infrastructure)\n4. Rising Trends (Sustainability, Digital adoption)\n\nSuggest 3 modifications to make this concept succeed locally.',
    goal: 'To adapt global business ideas specifically for the Bangladeshi market context.',
    category: 'Business',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Contextual',
    tokens: 180,
    temperature: 0.6,
    tags: ['#bangladesh', '#localization', '#market-entry'],
    views: 0,
    shares: 0,
    type: 'text',
    createdAt: Date.now(),
  },
  {
    id: 'lib-biz-5',
    title: 'Strategic Pricing Audit',
    prompt: 'You are conducting a pricing audit. My niche is [Niche]. My competitors price at [Competitor Price].\n\n1. Analyze my product costs (Materials, Labor, Marketing).\n2. Research customer price sensitivity in this niche.\n3. Recommend a pricing strategy (Lower, Higher, or Parity) to maximize profitability.\n4. Suggest 3 pricing tiers (Basic, Premium, Deluxe) to increase revenue potential using "Choice Architecture".',
    goal: 'To optimize pricing strategy for maximum profitability using behavioral psychology.',
    category: 'Business',
    llmModels: ['Claude', 'Gemini'],
    technique: 'Chain-of-Thought (CoT)',
    tokens: 150,
    temperature: 0.5,
    tags: ['#pricing', '#revenue', '#strategy'],
    views: 0,
    shares: 0,
    type: 'text',
    createdAt: Date.now(),
  },
  {
    id: 'lib-biz-6',
    title: 'Unfair Advantage Identifier',
    prompt: 'Act as a Competitive Advantage Analyst.\n\nMy proposed business is: [Business Idea].\nMy background is: [Skills/Experience].\n\nIdentify my "Unfair Advantage" - something that cannot be easily copied or bought by competitors.\nLook for:\n1. Insider Knowledge\n2. Unique Network/Community\n3. Personal Brand/Authority\n\nExplain how to weave this advantage into my brand story.',
    goal: 'To identify and leverage unique personal or business assets for competitive moats.',
    category: 'Business',
    llmModels: ['Claude', 'Gemini'],
    technique: 'Role-based',
    tokens: 130,
    temperature: 0.6,
    tags: ['#strategy', '#competition', '#branding'],
    views: 0,
    shares: 0,
    type: 'text',
    createdAt: Date.now(),
  },
  {
    id: 'lib-biz-7',
    title: 'Productized Service Architect',
    prompt: 'Act as a Productization Specialist.\n\nI currently offer [Service, e.g., Graphic Design] as a freelancer/agency.\n\nPropose 3 ways to turn this into a "Productized Service" (fixed scope, fixed price, scalable).\nFor each option, define:\n1. The Package (What is included/excluded)\n2. The Price Point\n3. The Target Customer\n4. The Delivery System (How to streamline it)',
    goal: 'To scale a service-based business by packaging it like a product.',
    category: 'Business',
    llmModels: ['ChatGPT', 'Gemini'],
    technique: 'Chain-of-Thought (CoT)',
    tokens: 160,
    temperature: 0.7,
    tags: ['#services', '#scaling', '#business-model'],
    views: 0,
    shares: 0,
    type: 'text',
    createdAt: Date.now(),
  },

  // --- STRATEGY ---
  {
    id: 'lib-strat-1',
    title: 'Blue Ocean Niche Finder',
    prompt: 'Act as a Blue Ocean Navigator. \n\n1. Analyze the [Industry/Category] market in [Region/Country]. List the top 3 most crowded/saturated areas.\n2. Identify an area of interest that ISN\'T overly represented.\n3. Apply the "Four Actions Framework":\n   - Eliminate: What features can be removed?\n   - Reduce: What can be simplified to lower costs?\n   - Raise: What can be elevated beyond norms?\n   - Create: What entirely new factor can be introduced?',
    goal: 'To identify uncontested market spaces and create new demand.',
    category: 'Strategy',
    llmModels: ['Claude', 'Gemini', 'ChatGPT'],
    technique: 'Chain-of-Thought (CoT)',
    tokens: 200,
    temperature: 0.8,
    tags: ['#blue-ocean', '#innovation', '#strategy'],
    views: 0,
    shares: 0,
    type: 'text',
    createdAt: Date.now(),
  },
  {
    id: 'lib-strat-2',
    title: 'SPIN Selling Needs Analysis',
    prompt: 'Act as a Sales Consultant using the SPIN framework (Situation, Problem, Implication, Need-Payoff).\n\nMy product is: [Product Name/Description].\nMy target customer is: [Target Audience].\n\nGenerate a script of questions I should ask a potential client:\n1. Situation Questions (Understand their reality)\n2. Problem Questions (Uncover pain points)\n3. Implication Questions (Highlight consequences of inaction)\n4. Need-Payoff Questions (Guide them to the solution)',
    goal: 'To create a powerful sales script that uncovers customer needs and closes deals.',
    category: 'Strategy',
    llmModels: ['ChatGPT', 'Claude'],
    technique: 'Role-based',
    tokens: 160,
    temperature: 0.6,
    tags: ['#sales', '#spin-selling', '#negotiation'],
    views: 0,
    shares: 0,
    type: 'text',
    createdAt: Date.now(),
  },
  {
    id: 'lib-strat-3',
    title: 'The "IKEA Effect" Strategy',
    prompt: 'Act as a Product Engagement Strategist.\n\nConcept: The IKEA Effect states that people value things more when they help create them.\n\nMy Product: [Product/Service].\n\nBrainstorm 3 ways to introduce "User Co-Creation" or "Assembly" into my product experience.\nExample: Customizable features, finishing steps done by user, inputs that shape the outcome.\n\nGoal: Increase perceived value and emotional ownership.',
    goal: 'To increase customer loyalty and perceived value by involving them in the creation process.',
    category: 'Strategy',
    llmModels: ['Gemini', 'Claude'],
    technique: 'Contextual',
    tokens: 140,
    temperature: 0.8,
    tags: ['#psychology', '#engagement', '#value-creation'],
    views: 0,
    shares: 0,
    type: 'text',
    createdAt: Date.now(),
  },
  {
    id: 'lib-strat-4',
    title: 'The "5 Whys" Root Cause Analysis',
    prompt: 'Act as a Needs Detective using the "5 Whys" technique.\n\nSurface Problem: [Problem my customer says they have].\n\nAsk "Why?" 5 times deeply to uncover the ROOT CAUSE of this problem.\nThen, propose a product feature or marketing angle that speaks directly to that root cause, rather than just the surface symptom.',
    goal: 'To identify the deep, underlying needs of customers for more resonant product positioning.',
    category: 'Strategy',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Iterative Prompting',
    tokens: 120,
    temperature: 0.5,
    tags: ['#problem-solving', '#root-cause', '#innovation'],
    views: 0,
    shares: 0,
    type: 'text',
    createdAt: Date.now(),
  },
  {
    id: 'lib-strat-5',
    title: 'Risky Assumption Test (RAT)',
    prompt: 'Act as a Pre-Launch Skeptic.\n\nMy Business Idea: [Idea].\n\nIdentify the 3 biggest "Risky Assumptions" that, if false, would kill this business (e.g., "People are willing to pay for X").\n\nFor each assumption, design a low-cost, quick experiment to validate it WITHOUT building the full product (e.g., Landing page test, Concierge MVP, Survey).',
    goal: 'To prevent failure by validating core business assumptions early and cheaply.',
    category: 'Strategy',
    llmModels: ['Claude', 'Gemini'],
    technique: 'Chain-of-Thought (CoT)',
    tokens: 150,
    temperature: 0.6,
    tags: ['#validation', '#risk-management', '#lean-startup'],
    views: 0,
    shares: 0,
    type: 'text',
    createdAt: Date.now(),
  },

  // --- PRODUCT MANAGEMENT ---
  {
    id: 'lib-prod-1',
    title: 'MVP (Minimum Viable Product) Strategist',
    prompt: 'Act as an MVP Strategist using Lean Startup methodology.\n\nMy full product vision is: [Full Vision].\n\n1. Strip it down to its ABSOLUTE core function that still delivers value.\n2. Propose a "low tech" MVP option (e.g., Spreadsheet instead of App, PDF instead of Course).\n3. Outline a plan to pre-sell or validate demand before building the full version.',
    goal: 'To save time and money by validating product ideas with minimal resources.',
    category: 'Product Management',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Chain-of-Thought (CoT)',
    tokens: 140,
    temperature: 0.5,
    tags: ['#mvp', '#product-launch', '#lean-startup'],
    views: 0,
    shares: 0,
    type: 'text',
    createdAt: Date.now(),
  },
  {
    id: 'lib-prod-2',
    title: 'Product Gamification Strategist',
    prompt: 'Act as a Gamification Guru.\n\nMy product is: [Product Name].\nThe core actions I want users to take are: [Actions].\n\nBrainstorm 3 gamification elements to increase engagement:\n1. Point Systems (Rewards for actions)\n2. Visual Progress (Bars, Streaks)\n3. Social Competition (Leaderboards, Challenges)\n\nAnalyze if these align with my target customer: [Target Customer].',
    goal: 'To increase user engagement and retention by adding game-like elements to products.',
    category: 'Product Management',
    llmModels: ['Claude', 'Gemini'],
    technique: 'Role-based',
    tokens: 150,
    temperature: 0.9,
    tags: ['#gamification', '#engagement', '#ux'],
    views: 0,
    shares: 0,
    type: 'text',
    createdAt: Date.now(),
  },
  {
    id: 'lib-prod-3',
    title: 'Feature Prioritization Matrix',
    prompt: 'Act as a Product Design Strategist.\n\nI have a list of potential features: [Feature 1, Feature 2, Feature 3, ...].\n\nCategorize these into a 2x2 Matrix:\n1. High Impact / Low Effort (Do these first - Quick Wins)\n2. High Impact / High Effort (Strategic Projects)\n3. Low Impact / Low Effort (Fillers)\n4. Low Impact / High Effort (Ignore)\n\nJustify the placement of the top 3 features.',
    goal: 'To effectively prioritize product development roadmap for maximum impact.',
    category: 'Product Management',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Chain-of-Thought (CoT)',
    tokens: 130,
    temperature: 0.5,
    tags: ['#prioritization', '#roadmap', '#strategy'],
    views: 0,
    shares: 0,
    type: 'text',
    createdAt: Date.now(),
  },
  {
    id: 'lib-prod-4',
    title: 'Customer Co-Creation Framework',
    prompt: 'Act as a Community-Driven Creator.\n\nI am building: [Product].\n\nIdentify 3 key decision points where I should ask for customer input (e.g., pricing, logo, specific feature).\nDraft a poll or question for each that makes the customer feel like an "Insider" or "Co-founder" of the product.\nExplain where to post these for best feedback (e.g., specific subreddits, FB groups).',
    goal: 'To build a product that users love by involving them in the development process.',
    category: 'Product Management',
    llmModels: ['Claude', 'Gemini'],
    technique: 'Role-based',
    tokens: 140,
    temperature: 0.7,
    tags: ['#community', '#feedback', '#product-dev'],
    views: 0,
    shares: 0,
    type: 'text',
    createdAt: Date.now(),
  },

  // --- CODING ---
  {
    id: 'lib-code-1',
    title: 'Code Explainer (ELI5)',
    prompt: 'Explain the following code snippet to me as if I were a 5-year-old (ELI5). Use a simple analogy and avoid technical jargon.\n\n```[language]\n[Paste code snippet here]\n```',
    goal: 'To understand complex code by breaking it down into a simple, easy-to-grasp explanation using an analogy.',
    category: 'Coding',
    llmModels: ['Gemini', 'Claude', 'DeepSeek'],
    technique: 'Zero-shot',
    tokens: 60,
    temperature: 0.5,
    tags: ['#learning', '#debugging', '#eli5'],
    views: 3500,
    shares: 950,
    type: 'text',
    createdAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'lib-code-2',
    title: 'Regex Pattern Generator',
    prompt: 'Generate a regular expression (regex) pattern that can be used to validate a [type of input, e.g., strong password, YouTube URL, username].\n\nHere are some examples of strings it should match:\n- "[example 1]"\n- "[example 2]"\n\nHere are some examples of strings it should NOT match:\n- "[example 3]"\n- "[example 4]"\n\nAlso, provide a brief explanation of how the regex works.',
    goal: 'To create a precise regex pattern based on examples of what should and should not match, including an explanation.',
    category: 'Coding',
    llmModels: ['Gemini', 'ChatGPT', 'Grok'],
    technique: 'Few-shot',
    tokens: 95,
    temperature: 0.4,
    tags: ['#regex', '#validation', '#development'],
    views: 4100,
    shares: 1100,
    type: 'text',
    createdAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'lib-code-3',
    title: 'API Response to Interface Converter',
    prompt: 'Act as a senior developer. Based on the following JSON API response, generate a corresponding interface or type definition in [language, e.g., TypeScript, Python dataclass].\n\nJSON Response:\n```json\n[Paste JSON object here]\n```',
    goal: 'To automatically generate code interfaces or types from a sample JSON response, saving time and reducing errors in development.',
    category: 'Coding',
    llmModels: ['Gemini', 'ChatGPT', 'Claude'],
    technique: 'Zero-shot',
    tokens: 60,
    temperature: 0.3,
    tags: ['#api', '#typescript', '#python', '#automation'],
    views: 2800,
    shares: 840,
    type: 'text',
    createdAt: Date.now() - 8 * 24 * 60 * 60 * 1000,
  },

  // --- CREATIVE ---
  {
    id: 'lib-creative-1',
    title: 'Story Starter with a Twist',
    prompt: 'Write the opening three paragraphs of a story in the [genre] genre. The story should begin with a common trope (e.g., "a detective gets a mysterious case"), but the third paragraph must introduce a completely unexpected twist that subverts the reader\'s expectations.',
    goal: 'To generate a creative and engaging story opening that hooks the reader with a familiar setup and then surprises them with a unique twist.',
    category: 'Creative',
    llmModels: ['Gemini', 'Claude'],
    technique: 'Zero-shot',
    tokens: 70,
    temperature: 1.0,
    tags: ['#writing', '#fiction', '#storytelling'],
    views: 1500,
    shares: 420,
    type: 'text',
    createdAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'lib-creative-2',
    title: 'Visual Trend Hunter',
    prompt: 'Act as a Visual Trend Scout.\n\nI am interested in the [Niche, e.g., Home Decor] niche.\n\n1. Browse (simulated) Instagram/Pinterest trends for this niche.\n2. Describe 3 emerging visual trends (colors, materials, aesthetics).\n3. Brainstorm how I could incorporate these trends into a new product line to make it feel fresh and current.',
    goal: 'To leverage visual trends for product development and marketing.',
    category: 'Creative',
    llmModels: ['Gemini', 'Midjourney'],
    technique: 'Role-based',
    tokens: 120,
    temperature: 0.9,
    tags: ['#design', '#trends', '#visuals'],
    views: 0,
    shares: 0,
    type: 'text',
    createdAt: Date.now(),
  },

  // --- EDUCATION ---
  {
    id: 'lib-edu-1',
    title: 'Concept Explainer with Analogy',
    prompt: 'Explain the complex scientific concept of [concept, e.g., "quantum entanglement", "photosynthesis"] to a high school student. First, provide a textbook-style definition. Then, create a simple and memorable real-world analogy to help solidify their understanding.',
    goal: 'To make a complex topic easier to understand by providing both a formal definition and a relatable analogy.',
    category: 'Education',
    llmModels: ['Gemini', 'Claude'],
    technique: 'Chain-of-Thought (CoT)',
    tokens: 75,
    temperature: 0.6,
    tags: ['#learning', '#teaching', '#analogy'],
    views: 1800,
    shares: 350,
    type: 'text',
    createdAt: Date.now() - 28 * 24 * 60 * 60 * 1000,
  },

  // --- IMAGE & VIDEO ---
  {
    id: 'lib-img-1',
    title: 'Cinematic Image Prompt',
    prompt: 'Create a highly detailed text-to-image prompt for an epic, cinematic shot. The scene is: [describe the scene, e.g., "a lone astronaut on a red desert planet"]. Include details about the lighting (e.g., "dramatic, low-key lighting"), camera angle (e.g., "low-angle shot"), and overall mood (e.g., "sense of isolation and wonder"). Specify "photorealistic, 8k, octane render" for style.',
    goal: 'To generate a rich, detailed prompt for text-to-image models that produces a specific, cinematic, and high-quality result.',
    category: 'Image & Video',
    llmModels: ['Imagen', 'Midjourney', 'Stable Diffusion', 'DALL-E'],
    technique: 'Zero-shot',
    tokens: 90,
    temperature: 0.8,
    tags: ['#midjourney', '#stable-diffusion', '#image-prompt'],
    views: 5200,
    shares: 1300,
    type: 'image',
    createdAt: Date.now() - 4 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'lib-vid-1',
    title: 'Short Video Script Outline',
    prompt: 'Create a shot-by-shot script outline for a 30-second promotional video about [product/service]. The video should be fast-paced and engaging for social media. For each shot (5-7 shots total), describe the visual and any accompanying text overlay or voiceover.',
    goal: 'To quickly create a structured outline for a short, engaging video, making the production process more efficient.',
    category: 'Image & Video',
    llmModels: ['Gemini', 'Sora', 'Veo', 'RunwayML'],
    technique: 'Zero-shot',
    tokens: 80,
    temperature: 0.7,
    tags: ['#video', '#script', '#social-media'],
    views: 1600,
    shares: 390,
    type: 'video',
    createdAt: Date.now() - 20 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'lib-vid-2',
    title: 'Digital Content Repurposer',
    prompt: 'Act as a Content Monetization Master.\n\nI have a piece of long-form content: [Link or Text of Blog/Video].\n\nBrainstorm 5 ways to repurpose this into different formats:\n1. Social Media Snippets (Twitter/LinkedIn)\n2. Short-form Video Script (TikTok/Reels)\n3. Downloadable PDF/Checklist\n4. Email Newsletter Blurb\n5. "Micro-Course" Outline\n\nGoal: Maximize reach with minimal new effort.',
    goal: 'To multiply the value of existing content across multiple platforms.',
    category: 'Image & Video',
    llmModels: ['Gemini', 'ChatGPT'],
    technique: 'Chain-of-Thought (CoT)',
    tokens: 140,
    temperature: 0.7,
    tags: ['#content-strategy', '#repurposing', '#social-media'],
    views: 0,
    shares: 0,
    type: 'text',
    createdAt: Date.now(),
  },
];
